import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "../styles/main.css";
import Login from "./login/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isLoggedIn = false;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {isLoggedIn ? (
          <>
            <Navbar />
            <main>{children}</main>
          </>
        ) : (
          <main
            style={{
              margin: "3rem",
            }}
          >
            <Login />
          </main>
        )}
      </body>
    </html>
  );
}
